# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: SitemapInstaller

on: workflow_dispatch
#on:
#  schedule:
#    - cron: '0 1 */2 * *' # cronで定期実行
#    - workflow_dispatch
jobs:
  Sitemap:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.YOUR_SELF_MADE_TOKEN }}

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          git fetch
          git pull
          python -m pip install --upgrade pip
          pip install pandas

      - name: Run main.py
        run: |
          python sitemap.py

      - name: git setting
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Commit and Push
        run: |
          git add . && git commit -m "Sitemap" && git push -u origin main || true
  deploy:
    runs-on: ubuntu-latest
    needs: [Sitemap]
    steps:
      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
