# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: ActionsTest # GitHub Actionsにつける名前。任意で良い。

# on:
#   schedule:
#     - cron: '0 3 * * *' # cronで定期実行

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest # 最新のubuntu環境で下記のジョブを実行
#     services:
#       selenium:
#         image: selenium/standalone-chrome:3.141.59-vanadium
#         ports:
#           - 4444:4444
#         volumes:
#           - /dev/shm:/dev/shm
          
    steps:
      - uses: actions/checkout@v2 # おまじない
      
      - name: Setup python # ワークフローのセクションごとに設定する名前。特に設定する必要はないが、どこでエラーが起きているかを把握する為にも設定しておいた方が良い。
        uses: actions/setup-python@v2 # Pythonのセットアップ
        with:
          python-version: "3.x" # Pythonのバージョン指定

      - name: Install dependencies # Pythonの依存環境のインストール
        run: | #このような書き方で複数行を一気に実行することができる。
          python -m pip install --upgrade pip
          pip install Flask
          pip install chromedriver-binary
          pip install selenium

      - name: Run main.py # Pythonファイルの実行
        run: |
          python main.py
      
      - name: git setting
        run: |
          git config --local user.email "keito.12.10@icloud.com"
          git config --local user.name "Tanesan"

      - name: Commit and Push # 実行した結果をプッシュして変更をレポジトリに反映
        run: |
          git add .
          git commit -m "Commit Message" -a
          git config pull.rebase false
          git pull
          git push origin main
      
      - name: Run main.py # Pythonファイルの実行
        run: |
          python main1.py
      - name: git setting
        run: |
          git config --local user.email "keito.12.10@icloud.com"
          git config --local user.name "Tanesan"

      - name: Commit and Push # 実行した結果をプッシュして変更をレポジトリに反映
        run: |
          git add .
          git commit -m "Commit Message" -a
          git config pull.rebase false
          git pull
          git push origin main
          
      - name: Run main.py # Pythonファイルの実行
        run: |
          python main1.py
      - name: git setting
        run: |
          git config --local user.email "keito.12.10@icloud.com"
          git config --local user.name "Tanesan"

      - name: Commit and Push # 実行した結果をプッシュして変更をレポジトリに反映
        run: |
          git add .
          git commit -m "Commit Message" -a
          git config pull.rebase false
          git pull
          git push origin main
          
      
      - name: Run main.py # Pythonファイルの実行
        run: |
          python main1.py
      - name: git setting
        run: |
          git config --local user.email "keito.12.10@icloud.com"
          git config --local user.name "Tanesan"

      - name: Commit and Push # 実行した結果をプッシュして変更をレポジトリに反映
        run: |
          git add .
          git commit -m "Commit Message" -a
          git config pull.rebase false
          git pull
          git push origin main
          
      - name: Run main.py # Pythonファイルの実行
        run: |
          python main2.py
      - name: git setting
        run: |
          git config --local user.email "keito.12.10@icloud.com"
          git config --local user.name "Tanesan"

      - name: Commit and Push # 実行した結果をプッシュして変更をレポジトリに反映
        run: |
          git add .
          git commit -m "Commit Message" -a
          git config pull.rebase false
          git pull
          git push origin main
      
      - name: Run main.py # Pythonファイルの実行
        run: |
          python main3.py
      - name: git setting
        run: |
          git config --local user.email "keito.12.10@icloud.com"
          git config --local user.name "Tanesan"

      - name: Commit and Push # 実行した結果をプッシュして変更をレポジトリに反映
        run: |
          git add .
          git commit -m "Commit Message" -a
          git config pull.rebase false
          git pull
          git push origin main
          
      - name: Run main.py # Pythonファイルの実行
        run: |
          python main4.py
      - name: git setting
        run: |
          git config --local user.email "keito.12.10@icloud.com"
          git config --local user.name "Tanesan"

      - name: Commit and Push # 実行した結果をプッシュして変更をレポジトリに反映
        run: |
          git add .
          git commit -m "Commit Message" -a
          git config pull.rebase false
          git pull
          git push origin main
          
      - name: Run main.py # Pythonファイルの実行
        run: |
          python main5.py
      - name: git setting
        run: |
          git config --local user.email "keito.12.10@icloud.com"
          git config --local user.name "Tanesan"

      - name: Commit and Push # 実行した結果をプッシュして変更をレポジトリに反映
        run: |
          git add .
          git commit -m "Commit Message" -a
          git config pull.rebase false
          git pull
          git push origin main
          
      - name: Run main.py # Pythonファイルの実行
        run: |
          python main6.py
      - name: git setting
        run: |
          git config --local user.email "keito.12.10@icloud.com"
          git config --local user.name "Tanesan"

      - name: Commit and Push # 実行した結果をプッシュして変更をレポジトリに反映
        run: |
          git add .
          git commit -m "Commit Message" -a
          git config pull.rebase false
          git pull
          git push origin main
          
      - name: Run main.py # Pythonファイルの実行
        run: |
          python main7.py
      - name: git setting
        run: |
          git config --local user.email "keito.12.10@icloud.com"
          git config --local user.name "Tanesan"

      - name: Commit and Push # 実行した結果をプッシュして変更をレポジトリに反映
        run: |
          git add .
          git commit -m "Commit Message" -a
          git config pull.rebase false
          git pull
          git push origin main
          
      - name: Run main.py # Pythonファイルの実行
        run: |
          python main8.py
      - name: git setting
        run: |
          git config --local user.email "keito.12.10@icloud.com"
          git config --local user.name "Tanesan"

      - name: Commit and Push # 実行した結果をプッシュして変更をレポジトリに反映
        run: |
          git add .
          git commit -m "Commit Message" -a
          git config pull.rebase false
          git pull
          git push origin main
          
      - name: Run main.py # Pythonファイルの実行
        run: |
          python main9.py
      - name: git setting
        run: |
          git config --local user.email "keito.12.10@icloud.com"
          git config --local user.name "Tanesan"

      - name: Commit and Push # 実行した結果をプッシュして変更をレポジトリに反映
        run: |
          git add .
          git commit -m "Commit Message" -a
          git config pull.rebase false
          git pull
          git push origin main
          
      - name: Run main.py # Pythonファイルの実行
        run: |
          python main10.py
      - name: git setting
        run: |
          git config --local user.email "keito.12.10@icloud.com"
          git config --local user.name "Tanesan"

      - name: Commit and Push # 実行した結果をプッシュして変更をレポジトリに反映
        run: |
          git add .
          git commit -m "Commit Message" -a
          git config pull.rebase false
          git pull
          git push origin main
          
      - name: Run main.py # Pythonファイルの実行
        run: |
          python main11.py
      - name: git setting
        run: |
          git config --local user.email "keito.12.10@icloud.com"
          git config --local user.name "Tanesan"

      - name: Commit and Push # 実行した結果をプッシュして変更をレポジトリに反映
        run: |
          git add .
          git commit -m "Commit Message" -a
          git config pull.rebase false
          git pull
          git push origin main
      
      - name: deploy
        uses: peaceiris/actions-gh-pages@v2.5.0
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: frontend/build
