# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: AllSubjectInstall_manual3


on: workflow_dispatch

jobs:
  Sitemap:
    runs-on: ubuntu-latest
    timeout-minutes: 720
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.YOUR_SELF_MADE_TOKEN }}

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          git fetch
          git pull
          python -m pip install --upgrade pip
          pip install pandas requests

      - name: Run main.py
        run: |
          python sitemap.py && python for_fuse.py

      - name: git setting
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"



      - name: Commit and Push
        run: |
          git add -N .
          if ! git diff --exit-code --quiet
          then
             python versionup.py
            git add . && git commit -m "Sitemap" && git push -u origin main
          fi
        

  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 720
    needs: Sitemap
    steps:
      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
