# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: ActionsTest # GitHub Actionsにつける名前。任意で良い。

# on:
#   schedule:
#     - cron: '0 3 * * *' # cronで定期実行

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest # 最新のubuntu環境で下記のジョブを実行
          
    steps:
      - uses: actions/checkout@v2 # おまじない
      
      - name: Setup python # ワークフローのセクションごとに設定する名前。特に設定する必要はないが、どこでエラーが起きているかを把握する為にも設定しておいた方が良い。
        uses: actions/setup-python@v2 # Pythonのセットアップ
        with:
          python-version: "3.x" # Pythonのバージョン指定

      - name: Install dependencies # Pythonの依存環境のインストール
        run: | #このような書き方で複数行を一気に実行することができる。
          python -m pip install --upgrade pip
          pip install Flask
          pip install chromedriver-binary
          pip install selenium

      - name: git setting
        run: |
            git config --local user.email "keito.12.10@icloud.com"
            git config --local user.name "Tanesan"

  build0:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Run main.py # Pythonファイルの実行
        run: |
          python define.py main.py

      - name: Commit and Push # 実行した結果をプッシュして変更をレポジトリに反映
        run: |
          git add .
          git commit -m "Commit Message" -a
          git config pull.rebase false
          git pull
          git push origin main
          
  build1:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Run main.py # Pythonファイルの実行
        run: |
          python define.py main1.py


      - name: Commit and Push # 実行した結果をプッシュして変更をレポジトリに反映
        run: |
          git add .
          git commit -m "Commit Message" -a
          git config pull.rebase false
          git pull
          git push origin main
  build2:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Run main.py # Pythonファイルの実行
        run: |
          python define.py main2.py


      - name: Commit and Push # 実行した結果をプッシュして変更をレポジトリに反映
        run: |
          git add .
          git commit -m "Commit Message" -a
          git config pull.rebase false
          git pull
          git push origin main
  build3:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Run main.py # Pythonファイルの実行
        run: |
          python define.py main3.py

      - name: Commit and Push # 実行した結果をプッシュして変更をレポジトリに反映
        run: |
          git add .
          git commit -m "Commit Message" -a
          git config pull.rebase false
          git pull
          git push origin main
  build4:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Run main.py # Pythonファイルの実行
        run: |
          python define.py main4.py

      - name: Commit and Push # 実行した結果をプッシュして変更をレポジトリに反映
        run: |
          git add .
          git commit -m "Commit Message" -a
          git config pull.rebase false
          git pull
          git push origin main
  build5:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Run main.py # Pythonファイルの実行
        run: |
          python define.py main5.py

      - name: Commit and Push # 実行した結果をプッシュして変更をレポジトリに反映
        run: |
          git add .
          git commit -m "Commit Message" -a
          git config pull.rebase false
          git pull
          git push origin main
  build6:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Run main.py # Pythonファイルの実行
        run: |
          python define.py main6.py
 
      - name: Commit and Push # 実行した結果をプッシュして変更をレポジトリに反映
        run: |
          git add .
          git commit -m "Commit Message" -a
          git config pull.rebase false
          git pull
          git push origin main
  build7:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Run main.py # Pythonファイルの実行
        run: |
          python define.py main7.py
 
      - name: Commit and Push # 実行した結果をプッシュして変更をレポジトリに反映
        run: |
          git add .
          git commit -m "Commit Message" -a
          git config pull.rebase false
          git pull
          git push origin main
  build8:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Run main.py # Pythonファイルの実行
        run: |
          python define.py main8.py

      - name: Commit and Push # 実行した結果をプッシュして変更をレポジトリに反映
        run: |
          git add .
          git commit -m "Commit Message" -a
          git config pull.rebase false
          git pull
          git push origin main
  build9:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Run main.py # Pythonファイルの実行
        run: |
          python define.py main9.py


      - name: Commit and Push # 実行した結果をプッシュして変更をレポジトリに反映
        run: |
          git add .
          git commit -m "Commit Message" -a
          git config pull.rebase false
          git pull
          git push origin main
  build10:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Run main.py # Pythonファイルの実行
        run: |
          python define.py main10.py

      - name: Commit and Push # 実行した結果をプッシュして変更をレポジトリに反映
        run: |
          git add .
          git commit -m "Commit Message" -a
          git config pull.rebase false
          git pull
          git push origin main
  build11:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Run define.py main11.py # Pythonファイルの実行
        run: |
          python main11.py

      - name: Commit and Push # 実行した結果をプッシュして変更をレポジトリに反映
        run: |
          git add .
          git commit -m "Commit Message" -a
          git config pull.rebase false
          git pull
          git push origin main
  deploy:
    runs-on: ubuntu-latest
    needs: [build0, build1, build2, build3, build4, build5, build6, build7, build8, build9, build10, build11]
    steps:
      - name: deploy
        uses: peaceiris/actions-gh-pages@v2.5.0
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: frontend/build
