
name: Post to Next

on:
  push:
    paths:
      - 'docs/all/*.json'

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Extract file names
        run: |
          git fetch
          files=$(git diff --name-only HEAD^ HEAD | grep 'docs/.*\.json' | cut -d/ -f2 | cut -d. -f1)
          echo "::set-output name=files::$files"
        id: extract
      
      - name: Post to Next
        if: ${{ steps.extract.outputs.files != '' }}
        env:
          API_SECRET_KEY: ${{ secrets.API_SECRET_KEY }}
        run: |
          files=${{ steps.extract.outputs.files }}
          curl -X POST -H "Content-Type: application/json" -d "{\"id\": \"$files\"}" https://subject.kgu-syllabus.com/?secret=$API_SECRET_KEY


