
name: Post to Next

on:
  push:
    paths:
      - 'docs/all/*.json'

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: technote-space/get-diff-action@v6
        with:
          PATTERNS: '*.json'
          RELATIVE: 'docs/all'
      - run: echo ${{ env.GIT_DIFF }}

      
      - name: Extract file names
        run: |
          files=$(env.GIT_DIFF | grep 'docs/all/.*\.json' | cut -d/ -f3 | cut -d/ -f2 | cut -d. -f1)
          echo "::set-output name=files::$files"
        id: extract
      
      - name: Post to Next
        if: ${{ steps.extract.outputs.files != '' }}
        env:
          API_SECRET_KEY: ${{ secrets.API_SECRET_KEY }}
        run: |
          files=${{ steps.extract.outputs.files }}
          curl -X POST -H "Content-Type: application/json" -d "{\"id\": \"$files\"}" https://subject.kgu-syllabus.com/?secret=$API_SECRET_KEY


