
name: Post to Next

on: push


jobs:
  Remove-Dubble:
    runs-on: ubuntu-latest
    timeout-minutes: 720
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.YOUR_SELF_MADE_TOKEN }}
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          git fetch
          git pull
          python -m pip install --upgrade pip

      - name: Run main.py
        run: |
          python dubble.py

      - name: git setting
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"



      - name: Commit and Push
        run: |
          git add -N .
          if ! git diff --exit-code --quiet
          then
            git add . && git commit -m "remove dubble" && git push -u origin main
          fi

  Sitemap:
    runs-on: ubuntu-latest
    timeout-minutes: 720
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.YOUR_SELF_MADE_TOKEN }}

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          git fetch
          git pull
          python -m pip install --upgrade pip
          pip install pandas

      - name: Run main.py
        run: |
          python sitemap.py && python for_fuse.py

      - name: git setting
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Commit and Push
        run: |
          git add -N .
          if ! git diff --exit-code --quiet
          then
             python versionup.py
            git add . && git commit -m "Sitemap" && git push -u origin main
          fi

  post:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: technote-space/get-diff-action@v6
        with:
          PATTERNS: '*.json'
          RELATIVE: 'docs/all'
      - run: |
          sleep 180
          curl -X POST -H "Content-Type: application/json" -d "{\"id\": $(echo \""$(echo ${{ env.GIT_DIFF }} | cut -d. -f1 | tr '\n' ',' | sed 's/,$//')"\")}" https://subject.kgu-syllabus.com/api/revalidate?secret=${{ secrets.API_SECRET_KEY }}  | jq .jobs
        id: extract
      
