name: Test Specific IDs

on:
  workflow_dispatch:
    inputs:
      ids:
        description: 'Comma-separated list of IDs to test'
        required: false
        default: '25050119,26459004'

jobs:
  test-specific-ids:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium==4.15.2
          
      - name: Install Chrome
        run: |
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          
      - name: Create test IDs file
        run: |
          echo '["${{ github.event.inputs.ids }}"]' | tr ',' '",' | sed 's/,"/","/g' > invalid_ids.json
          cat invalid_ids.json
          
      - name: Run test script
        run: |
          python test_specific_ids.py
          
      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: |
            test_*.png
            test_*.log
            test_problematic_ids.log
